### ISSUE TITLE
feat: add rule to disallow different versions of the same dependency in a mono-repo

### ISSUE THREAD

**Issue by mohanraj-r** [tclindner/npm-package-json-lint#655]
Different versions of dependencies (esp prod dependencies) in a mono-repo are problematic. It would be great to add a rule to check that only one version of a dependency is used across all packages in the mono-repo. If you are willing to accept a PR for this, I can try to create one with some guidance.

**Comment by tom-fletcher** [comment]
There is another package called [`syncpack`](https://jamiemason.github.io/syncpack/) that does exactly this. I would suggest using this instead of duplicating the functionality.

In my lint workflow, I run `npmPackageJsonLint . && syncpack lint` and this works very well.

@tclindner I would suggest this feature request could probably be closed?

**Comment by tclindner** [comment]
That sounds great, @tom-fletcher. Would you be okay if we add a call out to the docs to leverage your library? Thanks!

**Comment by tom-fletcher** [comment]
The library isn't mine - it is by @JamieMason - but it is stable and really good for checking/enforcing single-version version dependencies in monorepos. I've used it over a few projects.

**Comment by JamieMason** [comment]
Thanks everyone ❤️ that would be great.

**Comment by tclindner** [comment]
Docs added! Thanks everyone!
https://npmpackagejsonlint.org/docs/cli/
